### ISSUE TITLE
Crash browsing videos

### ISSUE THREAD

**Issue by Lppsoeht** [FossifyOrg/Gallery#157] opened 2024-03-05 06:20 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.1

### Affected Android/Custom ROM version

Latest GrapheneOs

### Affected device model

pixel 6

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

Viewing multiple videos/switching from any  video to any video. The problem probably has to do with autoplay

### Expected behavior

Multiple video browsing

### Actual behavior

Crash everytime

### Additional information

```
type: crash
package: org.fossify.gallery:5
process: org.fossify.gallery
processUptime: 24342 + 227 ms
installer: com.android.packageinstaller

java.lang.OutOfMemoryError: Failed to allocate a 64 byte allocation with 93656 free bytes and 91KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.view.WindowInsets$Builder.build(WindowInsets.java:1459)
	at k3.j2.i(SourceFile:1)
	at k3.k2.b(SourceFile:6)
	at k3.h2.e(SourceFile:5)
	at androidx.viewpager.widget.b.i(SourceFile:336)
	at k3.u0.onApplyWindowInsets(SourceFile:37)
	at android.view.View.dispatchApplyWindowInsets(View.java:11940)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7494)
	at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7519)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7501)
	at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7519)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7501)
	at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7519)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7501)
	at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7519)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7501)
	at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7519)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7501)
	at android.view.ViewGroup.newDispatchApplyWindowInsets(ViewGroup.java:7519)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7501)
	at android.view.ViewRootImpl.dispatchApplyInsets(ViewRootImpl.java:3031)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3495)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

**Comment by Aga-C** [comment] 2024-03-05 06:41
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/82.

**Closed by Aga-C** 2024-03-05 06:41 UTC
Labels: bug, needs triage
