### ISSUE TITLE
Maps for every photos

### ISSUE THREAD

**Issue by yusufsunetci** [FossifyOrg/Gallery#125] opened 2024-02-10 14:19 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

There is a map feature, but it is only for individual photos. It would be great if a feature to group photos according to the places taken on the Map tab and openstreetmaps map support were added. An open source program called Aves can be reviewed for this. The codes can be received there at the moment. It's a very nice feature.

### Why do you want this feature?

Being able to group according to the visited place will be a nice filter that will make it easier to find an image or video.
<img alt="IMG_20240210_171933" src="https://github.com/FossifyOrg/Gallery/assets/154959269/ea024add-f1f7-494a-9f7c-63a9b9bdd879" width=397 />

**Comment by Aga-C** [comment] 2024-02-10 14:33
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/83.

**Closed** 2024-02-10 14:33 UTC
Labels: feature request, needs triage
