### ISSUE TITLE
RAW dng files are blurred and have fewer zoom capabilities

### ISSUE THREAD

**Issue by CTappe** [FossifyOrg/Gallery#239] opened 2024-06-04 10:23 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.3

### Affected Android/Custom ROM version

Android 14

### Affected device model

Xiaomi Mi 11 Ultra

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open a raw dng file
2. Compare the raw file with the jpg version if available
3. Or compare the raw file with another gallery

### Expected behavior

The dng file should not look blurry. 
Also, when deep zoomable images are enabled, I would expect to be able to zoom into the dng file just as much as the same jpg file with the same resolution.

### Actual behavior

The raw files from my camera and from my smartphone (dng format each) are blurry if I view them in the Fossify Gallery. Also I can not zoom in as much I can in the jpg version.

### Screenshots/Screen recordings

**Comparison small dng file**
<img alt="Screenshot_2024-06-04-11-59-17-928_com miui gallery" src="https://github.com/FossifyOrg/Gallery/assets/171605614/37fa47bb-fa5a-4dc1-8913-6f6374d19576" width=180 />

**Comparison large dng file**
<img alt="Screenshot_2024-06-04-12-02-34-254_com miui gallery" src="https://github.com/FossifyOrg/Gallery/assets/171605614/66838a79-b34e-4314-9604-2c909c6e8ba5" width=180 />

**Small dng**
[DNG Original.zip](https://github.com/user-attachments/files/15546448/DNG.Original.zip)

**dng converted to jpg**
![IMG_20230801_152145_1](https://github.com/FossifyOrg/Gallery/assets/171605614/0eff111c-36de-41eb-8ea2-9f38f82d37ec)

### Additional information

I had to zip the dng file because of upload restrictions (no dng files allowed).
I noticed that I can zoom in less in larger dng files (those from my camera) than in smaller dng files (those from my smartphone). Larger dng files look far more blurry (see second screenshot).

**Comment by Aga-C** [comment] 2024-07-03 08:17
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/2.

**Closed by Aga-C** 2024-07-03 08:17 UTC
Labels: bug
