### ISSUE TITLE
Google camera Top shot

### ISSUE THREAD

**Issue by timechips** [FossifyOrg/Gallery#385] opened 2024-12-28 19:25 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Google camera has an option to take a short video while it takes a picture. The file has .MP.jpg extension and according to my limited knowledge I believe the video is stored in image metadata. The libre gallery Aves has this implemented. It would be nice if the video playback acted as a gif and looped after long press on image.

### Why do you want this feature?

New format support.

**Comment by Aga-C** [comment] 2024-12-28 19:58
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/59.

**Closed by Aga-C** 2024-12-28 19:58 UTC
Labels: feature request, needs triage
