### ISSUE TITLE
Preview mode

### ISSUE THREAD

**Issue by Lppsoeht** [FossifyOrg/Gallery#244] opened 2024-06-21 14:33 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

An optional feature to preview pictures(idk about videos) on long press or other gestures.
Like iPhone default gallery.

### Why do you want this feature?

Sometimes when I'm selecting multiple pictures(select mode) I need to see a specific photo to know if I've to select it too, but I cannot do it without deselecting everything and clicking on it.

**Comment by Aga-C** [comment] 2024-06-21 14:47
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/210.

**Closed by Aga-C** 2024-06-21 14:47 UTC
Labels: feature request, needs triage
