### ISSUE TITLE
Progress Indicator

### ISSUE THREAD

**Issue by GrennKren** [FossifyOrg/Gallery#356] opened 2024-11-10 16:41 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Can this be add a status indicator in the notification area to show the current scanning progress? 

### Why do you want this feature?

In Aves, I can see how many folders out of the total are being scanned right from the start. Since I have a lot of folders with many of images in each, this feature is quite helpful, it’s better than just waiting for the loading spinner to finish refreshing for new folders in the app

**Comment by Aga-C** [comment] 2024-11-10 17:04
It's a duplicate of https://github.com/FossifyOrg/General-Discussion/issues/120.

**Closed by Aga-C** 2024-11-10 17:04 UTC
Labels: feature request, needs triage
