### ISSUE TITLE
Add the ability to zoom out smaller images instead of fitting the screen

### ISSUE THREAD

**Issue by sam-gq** [FossifyOrg/Gallery#211] opened 2024-04-23 00:34 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

On a small image, I want to zoom out the image to its minimum, that the image viewer fits the downscaled image on the device's screen.

In example, I have an image that has 184x184 pixels. So I want to zoom out the image to its smaller size. Since I have a 720p screen, I'll be able to pinch it towards the two finger to scale down image that matches the screen details.

<details>
<summary>See sample video</summary>
<br>

https://github.com/FossifyOrg/Gallery/assets/80607823/bb67e9a8-25cd-4d11-8966-7d24ec2b4f1e
</details>

Since Fossify Gallery does not have a feature to zoom out smaller images on a large screen like this, I'll not be able to see fit the downscaled image on a large 720p screen.

<details>
<summary>See sample video</summary>
<br>

https://github.com/FossifyOrg/Gallery/assets/80607823/05fcf0e4-6457-4bc3-949d-67e85fb57709
</details>

### Why do you want this feature?

I use the zoom out feature, used for making a small icons or stickers.

### Additional information

As an example from QuickPic Gallery, a modified version by WSTxda.

**Comment by Aga-C** [comment] 2024-04-23 05:12
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/196.

**Closed by Aga-C** 2024-04-23 05:12 UTC
Labels: feature request, needs triage
