### ISSUE TITLE
Ui6 broke the slideshow feature 

### ISSUE THREAD

**Issue by countbranca** [FossifyOrg/Gallery#127] opened 2024-02-12 22:24 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.1

### Affected Android/Custom ROM version

Android 14

### Affected device model

S22, S24

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Got to slideshow, Go through prompts, hit start, all it does is stop at the first picture 

### Expected behavior

To do a slideshow

### Actual behavior

No slideshow

**Comment by Aga-C** [comment] 2024-02-12 22:29
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/35.

**Closed by Aga-C** 2024-02-12 22:29 UTC
Labels: bug, needs triage
