### ISSUE TITLE
Gallery: Delayed loading.

### ISSUE THREAD

**Issue by Cortru619** [FossifyOrg/Gallery#287] opened 2024-08-26 07:06 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.3

### Affected Android/Custom ROM version

Android 14

### Affected device model

Galaxy s24 ultra

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1.Open app.
2. App opens, can only see search bar and a blank screen for a moment, then the app loads.

There is just a delay loading the thumbnails, I tried using the gif moving feature on thumbnails at one point but the gifs wouldn't move/motion while in the main gallery.
Also, I took a screen record and it is a 3 second delay, I also tried changing the amount of thumbnails shown, clear3d cache and date. Forcestopped and tried reinstalling the app via gitgub.

### Expected behavior

Smoother loading speed opening the app. Thank you, by the way. 

### Actual behavior

Just a 3 second delay opening the app and the gifs don't ha e motion in the main gallery.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/30b0c21e-e922-479b-9cec-3d256e2a1610

### Additional information

I tried changing my phones animation speed via developer  options and system ui tuner. Same issue occured.

**Comment by Aga-C** [comment] 2024-08-26 07:17
After those 3 seconds, does the content appear at once, or does it just show one after another?

**Comment by Cortru619** [comment] 2024-08-26 15:23
Hello,

So the thumbnails will load 1 by 1 but once the thumbnails start to load
it's pretty quick noticed a slight delay just when opening the app and
trying to scroll down far.

**Comment by Aga-C** [comment] 2024-08-26 15:38
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/54.

**Closed by Aga-C** 2024-08-26 15:38 UTC
Labels: bug, question, needs triage
