### ISSUE TITLE
Transparent png having a black background 

### ISSUE THREAD

**Issue by pdimu** [FossifyOrg/Gallery#311] opened 2024-09-27 20:48 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.1

### Affected Android/Custom ROM version

Android 12 / MIUI 13 Global

### Affected device model

Redmi Note 9

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Find a folder with a transparent png as thumbnail 
2. Look at the preview of it

### Expected behavior

The background of the png should be transparent, not black

### Actual behavior

It's displaying a black background on transparent pngs

### Screenshots/Screen recordings

![Screenshot_2024-09-27-23-34-19-239-edit_org fossify gallery](https://github.com/user-attachments/assets/c4c6d078-0ed1-4a34-9543-a2e960a01ca7)

**Comment by Aga-C** [comment] 2024-09-27 21:10
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/261.

**Closed by Aga-C** 2024-09-27 21:10 UTC
Labels: bug, needs triage

**Comment by pdimu** [comment] 2024-09-28 05:28
@Aga-C I think you got me wrong. I don't want the pngs to have the black background, just like it was in older releases

**Comment by Aga-C** [comment] 2024-09-28 05:46
That request is about toggling transparency on and off. In fact, we had transparency in thumbnails, but when #261 will be done, it will affect both thumbnails and preview. You can add your remarks about thumbnails there.
