### ISSUE TITLE
images taken with front facing camera rotate 180° when veiwed

### ISSUE THREAD

**Issue by patritha** [FossifyOrg/Gallery#316] opened 2024-09-28 22:14 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.1

### Affected Android/Custom ROM version

Project Matrixx 10.7.3

### Affected device model

Google Pixel 6a

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

take a picture with the front facing camera, go to the app, click on the picture, watch it flip

### Expected behavior

its not supposed to flip 180 when you click in the picture

### Actual behavior

half a second after you click on a the picture it flips 180°

### Screenshots/Screen recordings

https://drive.google.com/file/d/1-8d1G-Wc3JcGnttg4kZcJ5MTLRXQ19Wq/view?usp=drivesdk

**Comment by Aga-C** [comment] 2024-09-29 05:51
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/107.

**Closed by Aga-C** 2024-09-29 05:51 UTC
Labels: bug, needs triage
