### ISSUE TITLE
Disable fade-in and/or all animations

### ISSUE THREAD

**Issue by emandtf** [FossifyOrg/Gallery#192] opened 2024-04-02 22:35 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Navigating folders all these "fade-in" animations of folders and files are very "boring" and slow.

**Can you add an option to avoid them?**

I specifically disabled all animations via "Development options" in my Android because it improves speed but the animation is still present in this App as I described.

### Why do you want this feature?

Performance improvement

**Comment by Aga-C** [comment] 2024-04-03 05:50
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/136.

**Closed** 2024-04-03 05:50 UTC
Labels: feature request, needs triage

**Comment by emandtf** [comment] 2024-04-03 06:01
LoL....closed as NOT PLANNED 😅
It's a "feature request" and I think all non-already-existent features were not planned at the time of the relative Request.

Putting a checkbox in Settings to avoid using an Android Animator is so much difficult to do?

**Comment by Aga-C** [comment] 2024-04-03 06:12
See my comment above, it's closed because it is DUPLICATE. We don't want to use "completed" for closed issues that are duplicates.

**Comment by emandtf** [comment] 2024-04-03 06:21
I suggest to put "animation" somewhere in that Feature Request text because I searched by that world before open this duplicate.
This will help others to avoid open another duplicated request in future.
