### ISSUE TITLE
Exif data can't be removed from images stored on the SD card

### ISSUE THREAD

**Issue by Uneccessary** [FossifyOrg/Gallery#187] opened 2024-03-26 23:22 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.2

### Affected Android/Custom ROM version

Android 14

### Affected device model

Samsung Galaxy A33 5G

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Take a photo if and save it with metadata attached to the SD card.
2. Open Fossify Gallery and go to the picture in the app
3. Click on the (i)
4. See that the remove Exif data option is missing, even if there is exif data which can be removed
5. Move the picture to the internal storage
6. Click again on (i)
7. Exif data can be removed

### Expected behavior

That the exif data removal option is also avaible for images stored on the SD card

### Actual behavior

The option for removing exif data is completly missing and non-avaible.

### Additional information

- All necessary permissions has been given to the app and it has full access to all files and SD card.

**Comment by Aga-C** [comment] 2024-03-27 06:14
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/60.

**Closed** 2024-03-27 06:14 UTC
Labels: bug, needs triage

**Comment by Uneccessary** [comment] 2024-03-28 18:52
Oh, I apologize I completly forgot abt that I've already opened an issue about, also, you have closed this as "not planned"? Does this mean, this issue won't be fixed?

**Comment by naveensingh** [comment] 2024-03-28 18:58
> Oh, I apologize I completly forgot abt that I've already opened an issue about, also, you have closed this as "not planned"? Does this mean, this issue won't be fixed?

@Uneccessary "not planned" doesn't necessarily mean it won't be fixed, it's just better than "closed as completed".
