### ISSUE TITLE
Mosaic view for albums.

### ISSUE THREAD

**Issue by UniverseCodex01** [FossifyOrg/Gallery#143] opened 2024-02-23 03:59 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [x] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Mosaic view on albums, like on Aves Gallery and Google Photos gallery.

### Why do you want this feature?

List view and grid view are not comfortable on my opinion, Mosaic view is more beautiful and more useful because you can see all picture content without opening it.

### Additional information

Mosaic view example:

<img alt="Screenshot_2024-02-23-00-58-33-020_com google android apps photos" src="https://github.com/FossifyOrg/Gallery/assets/93066706/2755d69c-5c94-41c4-be76-748d1f146544" width=200 />

**Comment by Aga-C** [comment] 2024-02-23 05:56
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/13.

**Closed by Aga-C** 2024-02-23 05:56 UTC
Labels: feature request, needs triage
