### ISSUE TITLE
Toolbar does not disappear anymore when turning device to landscape mode

### ISSUE THREAD

**Issue by rak-rak** [FossifyOrg/Gallery#331] opened 2024-10-13 14:09 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

v1.2.1

### Affected Android/Custom ROM version

Android 14

### Affected device model

Tablet Samsung Galaxy S9

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Open a folder in portrait mode
2. Tap on image to hide toolbar
3. Turn device to landscape mode
4. Try to tap on image 

### Expected behavior

Expected: Toolbar disappears when tapping on image

### Actual behavior

Nothing happens, toolbar stays visible on image view. 

### Additional information

Further information:
- The issue does not happen when opening a folder in landscape mode already
- The issue does not happen e.g. on my Phone Samsung S22+. Only on tablet. 
- The issue is also present in last version of simple mobile gallery

**Comment by Aga-C** [comment] 2024-10-13 14:26
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/275.

**Closed** 2024-10-13 14:26 UTC
Labels: bug, needs triage
