### ISSUE TITLE
Request: text tool into edit tool next to crop, doodle and filters.

### ISSUE THREAD

**Issue by DB9-max** [FossifyOrg/Gallery#361] opened 2024-11-19 03:41 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Request: text tool into edit tool next to crop, doodle and filters.

### Why do you want this feature?

See additional info

### Additional information

I like Fossify Gallery and don't want to use a second app for adding text, such as https://github.com/burhanrashid52/PhotoEditor

**Comment by Aga-C** [comment] 2024-11-19 06:34
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/97.

**Closed by Aga-C** 2024-11-19 06:34 UTC
Labels: feature request, needs triage
