### ISSUE TITLE
A little bug in dialog "Select Destination"

### ISSUE THREAD

**Issue by Astoritin** [FossifyOrg/Gallery#353] opened 2024-11-03 05:01 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.1

### Affected Android/Custom ROM version

Android 11 Crdroid 7.41 and Android 14 Project Matrixx 10.9.0

### Affected device model

Redmi Note 5 Pro

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Select a picture.
2. Click on the menu button.
3. Choose "Move to" or "Copy to" is okay
4. Click on the inputbox in "Select Destination" dialog and type any words
5. Click on the backspace button in any input method

### Expected behavior

The words/letters insides the inputbox will be deleted one by one as clicking on the input method's backspace button

### Actual behavior

It doesn't respond at all, all the words still remained in the inputbox. Only clicking on the delete【x】 button provided by UI can clean the text but it will erase all these words.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/58338239-ad23-4b05-b2e3-62dea7109ff5

### Additional information

Many time I only want to correct the words I typed instead of deleting all the words and type again, and I don't think it is healthy behavior either.

**Comment by Aga-C** [comment] 2024-11-03 05:53
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/145.

**Closed by Aga-C** 2024-11-03 05:53 UTC
Labels: bug, needs triage

**Comment by Astoritin** [comment] 2024-11-03 07:17
I see, it seems hopeless to fix this one. Sorry for disturbing you.
