### ISSUE TITLE
slow thumbnail loading

### ISSUE THREAD

**Issue by shockergit** [FossifyOrg/Gallery#357] opened 2024-11-13 10:21 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

latest from fdroid

### Affected Android/Custom ROM version

a13

### Affected device model

samsung a22

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1

### Expected behavior

Fast loading

### Actual behavior

Sluggish

### Additional information

The thumbnail loading is too slow comparing to other galleries including simple gallery

**Comment by Aga-C** [comment] 2024-11-13 11:05
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/54.

**Closed by Aga-C** 2024-11-13 11:05 UTC
Labels: bug, needs triage
