### ISSUE TITLE
Bad quality after opening a picture again

### ISSUE THREAD

**Issue by Richard38907** [FossifyOrg/Gallery#314] opened 2024-09-28 09:52 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.1

### Affected Android/Custom ROM version

Pixel experience 13 A13

### Affected device model

OnePlus Nord

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

Open a picture
Go back or switch to another picture
Open the first picture again
See the bad quality

### Expected behavior

Displaying in high quality

### Actual behavior

Bad quality

### Screenshots/Screen recordings

First time 
![Screenshot_20240928-114830_Galerie](https://github.com/user-attachments/assets/3863359a-9873-4d85-8abb-5cc944a28bbf)
Second time
![Screenshot_20240928-114844_Galerie](https://github.com/user-attachments/assets/3e43bf17-a864-4682-923a-f11ca2a40d90)

**Comment by Aga-C** [comment] 2024-09-28 09:57
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/289.

**Closed by Aga-C** 2024-09-28 09:57 UTC
Labels: bug, needs triage
