### ISSUE TITLE
Add a Masonry/Mosiac grid option

### ISSUE THREAD

**Issue by hitoridoga** [FossifyOrg/Gallery#173] opened 2024-03-21 15:21 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Lots of galleries over the years (even the default one, atleast for samsung) has had a masonry grid option which instead of every image in a cropped square grid, has the images in the correct ratio and size, placed together. The example i use is not even from a gallery app, however one quick google search will show exactly what i mean if you need to be sure.

<img alt="Screenshot_20240321_161659_Boorusama" src="https://github.com/FossifyOrg/Gallery/assets/71557599/eae50f6b-0c36-4eed-b8bd-91ff3b651333" width=205 />

### Why do you want this feature?

Previewing images looks alot better in masonry form rather than having them cropped and needing to click on them, i know theres an option to not have thumbnails cropped, however it does not look good and is not the same as the masonry grid.

**Comment by Aga-C** [comment] 2024-03-21 15:24
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/13.

**Closed by Aga-C** 2024-03-21 15:24 UTC
Labels: feature request, needs triage
