### ISSUE TITLE
Not able to open loaded images when loading rest of images.

### ISSUE THREAD

**Issue by lucas-mior** [FossifyOrg/Gallery#346] opened 2024-10-28 23:45 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.1

### Affected Android/Custom ROM version

Android 14

### Affected device model

Samsung A53

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Have lots (~100) of folders and images inside them, then open the app.

### Expected behavior

To load the content asynchronously, so that the user can open files before the loading of the other files end.

### Actual behavior

While the app loads the files, the user can't open the ones that have already been loaded. I can click, but nothing happens.

**Comment by Aga-C** [comment] 2024-10-29 05:56
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/54.

**Closed by Aga-C** 2024-10-29 05:56 UTC
Labels: bug, needs triage
