### ISSUE TITLE
Disable moving and copying folders

### ISSUE THREAD

**Issue by herrbrixter** [FossifyOrg/Gallery#220] opened 2024-05-01 21:08 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Remove "Move to" and "Copy to" options when selecting a folder in the folder view

### Why do you want this feature?

I accidentally moved a folder containing a lot of pictures into another folder because I thought I was just moving the folder's preview photo. I thought I was browsing pictures within a folder. It caused me to move 1,200 photos/videos and the app hanged. Related to issue #137 

The above functionality is redundant since users have another way of moving an entire folder by going inside a folder and using "Select all". This is a more conscious procedure which avoids accidentally moving the whole folder.

**Comment by Aga-C** [comment] 2024-05-01 21:36
Closing as a duplicate of https://github.com/FossifyOrg/Gallery/issues/137 because it was one of the suggested solutions there.

**Closed by Aga-C** 2024-05-01 21:36 UTC
Labels: feature request, needs triage
