### ISSUE TITLE
Can't hide ui in fullscreen mode after rotating

### ISSUE THREAD

**Issue by RatzzFatzz** [FossifyOrg/Gallery#288] opened 2024-08-27 10:05 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.3

### Affected Android/Custom ROM version

Android 14 / Project Matrixx

### Affected device model

Poco F5

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open picture in fullscreen
2. Make the UI shown
3. Rotate the device and click the rotation button (system auto rotation is deactivated)
4. Try to hide the UI

### Expected behavior

UI should be hidden when I click the screen.
If 'hide ui automatically' is active, the behavior is inverted and the UI can't be shown anymore.

### Actual behavior

UI is shown

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/772a27dd-928c-4727-812b-ac36cc8ae223

### Additional information

Device is rooted

**Comment by Aga-C** [comment] 2024-08-27 10:40
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/275.

**Closed by Aga-C** 2024-08-27 10:40 UTC
Labels: bug, needs triage
