### ISSUE TITLE
App is too slow, locks the app while in use. 

### ISSUE THREAD

**Issue by tikendraw** [FossifyOrg/Gallery#364] opened 2024-11-30 11:16 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

* It should have a faster way to update changes in files and update the viewport/screen when user have large number of files.
* It shouldn't lock the app while in active use, (it locks the app, when you are watching videos and try to go back to list again)

### Why do you want this feature?

See i have alot of images and videos in my phone, so when you try to delete , or rename any files it takes alot of time. like if you do delete lets say 4 files, it takes a second or 2 to update the changes, 

also if you are watching a video for some time and try to go back to files list, it locks the app, you have to unlock it to go the files list. (why? i am in the app, why it is locking)

**Comment by Aga-C** [comment] 2024-11-30 11:20
It's a duplicate of https://github.com/FossifyOrg/Gallery/issues/54.

**Closed by Aga-C** 2024-11-30 11:20 UTC
Labels: feature request, needs triage
