### ISSUE TITLE
Support spherical photos

### ISSUE THREAD

**Issue by matthiakl** [FossifyOrg/Gallery#272] opened 2024-07-26 11:05 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I remember the old SimpleTools Gallery supported spherical photos. You could tap it to switch into view mode and then look around by swiping.

### Why do you want this feature?

Currently photos taken by a photo sphere app are only displayed in their distorted flat form. This feature would allow to view those images without having to take out your VR frame.

**Comment by naveensingh** [comment] 2024-07-26 11:08
Isn't this a duplicate of https://github.com/FossifyOrg/Gallery/issues/42?

**Closed** 2024-07-26 12:00 UTC
Labels: feature request, needs triage
